# Generated by Django 6.0 on 2026-01-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_livro_delete_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='livro',
            new_name='Livros',
        ),
    ]
